site_name: MJ'S KNTU Notes
copyright: "ساخته شده با مقادیر فراوان چای و حوصله بسیار توسط MJBakhshi"

theme:
  name: sarv
  language: fa
  show_title: true
  icon: Group 1w.png
  favicon: Group 1w.png

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mjb4khshi/

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/translate.js

plugins:
  - search
  - ezlinks:
      wikilinks: false 
  - callouts
  - glightbox
  - awesome-pages

hooks:
  - mkdocs_theme_sarv/hooks/obsidian_engine.py

markdown_extensions:
  - md_in_html
  - admonition
  - wikilinks
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - nl2br
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true